"""add email and remove phone from org out

Revision ID: 23347f032efb
Revises: 76c7b267cc43
Create Date: 2024-03-15 01:03:21.135522

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '23347f032efb'
down_revision = '76c7b267cc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
