"""Add organization to User and members to Organization

Revision ID: 3b6d9e24c1d4
Revises: 6ff4f1697f18
Create Date: 2024-03-14 02:06:52.279768

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b6d9e24c1d4'
down_revision = '6ff4f1697f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
