"""add emails to organizations

Revision ID: 76c7b267cc43
Revises: 62b3e1b49207
Create Date: 2024-03-14 22:56:48.656480

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '76c7b267cc43'
down_revision = '62b3e1b49207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
