"""Add organization_id to vehicle model

Revision ID: 93b441811b93
Revises: 487130a2d6a8
Create Date: 2024-03-14 01:01:31.111149

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93b441811b93'
down_revision = '487130a2d6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicle', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.drop_column('vehicle', 'organization_id')
    # ### end Alembic commands ###
